# Starting yaml travis ci integration file

language: node_js
node_js:
   - "6"
   - "8"
   - "9"
cache:
  directories:
    - ~/.npm
before_install:
  # package-lock.json was introduced in npm@5
  - npm install -g npm@latest
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm run build
  - npm test
after_script: greenkeeper-lockfile-upload  
sudo: false
